<?php

namespace App\Consumable;

use App\Entity\Human;

abstract class Consumable {
  public function __construct(
    protected string $name,
    protected string $description = ''
  ) {
  }

  public function getName(): string {
    return $this->name;
  }

  public function getDescription(): string {
    return $this->description;
  }

  /**
   * @return array[] List of messages generated by using the item (each message is ['emoji' => string, 'text' => string])
   */
  abstract public function consume(Human $target): array;
}